platform :ios, '8.4'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'MD5Digest','~>1.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'SDWebImage', '~> 3.7.5' 
pod 'Masonry', '~> 1.0.0'
pod 'UMengSocialCOM', '~> 5.2.1'

